version: "3.8"
services:
  api:
    networks:
      - default
      - traefik

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-api.rule=Host(`api.${ENVIRONMENT}mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-api.entrypoints=websecure"
        - "traefik.http.routers.mlmodelscope-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.mlmodelscope-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowMethods=GET,OPTIONS,PUT,DELETE"
        - "traefik.http.middlewares.add-cors.headers.accesscontrolalloworiginlist=https://${ENVIRONMENT}mlmodelscope.org"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowCredentials=true"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowHeaders=origin,x-requested-with,content-type,accept,x-request-id"
        - "traefik.http.middlewares.add-cors.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.add-cors.headers.addvaryheader=true"
        - "traefik.http.routers.mlmodelscope-api.middlewares=add-cors"

  companion:
    networks:
      - default
      - traefik

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-companion.rule=Host(`companion.${ENVIRONMENT}mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-companion.entrypoints=websecure"
        - "traefik.http.routers.mlmodelscope-companion.tls.certresolver=letsencrypt"
        - "traefik.http.services.mlmodelscope-companion.loadbalancer.server.port=3020"
        - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowMethods=GET,OPTIONS,POST"
        - "traefik.http.middlewares.add-cors-companion.headers.accesscontrolalloworiginlist=https://${ENVIRONMENT}mlmodelscope.org"
        - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowCredentials=true"
        - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowHeaders=origin,content-type,accept,uppy-versions"
        - "traefik.http.middlewares.add-cors-companion.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.add-cors-companion.headers.addvaryheader=true"
        - "traefik.http.routers.mlmodelscope-companion.middlewares=add-cors-companion"

    environment:
      COMPANION_AWS_KEY: "$COMPANION_AWS_KEY"
      COMPANION_AWS_SECRET: "$COMPANION_AWS_SECRET"
      COMPANION_AWS_BUCKET: "$COMPANION_AWS_BUCKET"
      COMPANION_AWS_REGION: "$COMPANION_AWS_REGION"
      COMPANION_DOMAIN: "https://companion.${ENVIRONMENT}mlmodelscope.org"

    volumes:
      - staging-companion-data:/data

  mq:
    networks:
      - default
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-mq.rule=Host(`mq.${ENVIRONMENT}mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-mq.entrypoints=websecure"
        - "traefik.http.routers.mlmodelscope-mq.tls.certresolver=letsencrypt"
        - "traefik.http.services.mlmodelscope-mq.loadbalancer.server.port=15672"
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.conf
      - source: rabbitmq_definitions
        target: /etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_NODENAME: "$RABBITMQ_NODENAME"
    volumes:
      - staging-rabbit-efs:/var/lib/rabbitmq/mnesia

  consul:
    configs:
      - source: consul_config
        target: /consul/config/server.json
    volumes:
      - consul_data:/consul/data

### Monitoring services

  grafana:
    configs:
      - source: grafana_dashboards_config
        target: /etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - source: grafana_prometheus_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.grafana.rule=Host(`monitoring.${ENVIRONMENT}mlmodelscope.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    networks:
      - default
      - traefik

    volumes:
      - grafana_dashboards:/dashboards
      - grafana_data:/var/lib/grafana

  prometheus:
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus

configs:
  consul_config:
    external: true
  grafana_dashboards_config:
    external: true
  grafana_prometheus_datasource:
    external: true
  prometheus_config:
    external: true
  rabbitmq_config:
    external: true
  rabbitmq_definitions:
    external: true

networks:
  traefik:
    external: true
    name: traefik

volumes:
  staging-rabbit-efs:
    external: true
  staging-companion-data:
  consul_data:
  grafana_dashboards:
  grafana_data:
  prometheus_data:

