services:
  api:
    image: "$DOCKER_REGISTRY/mlmodelscope-api:$API_VERSION"

    environment:
      - DB_DBNAME=$DB_DBNAME
      - DB_DRIVER=$DB_DRIVER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - MQ_HOST=$MQ_HOST
      - MQ_PORT=$MQ_PORT
      - MQ_USER=$MQ_USER
      - MQ_PASSWORD=$MQ_PASSWORD
      - TRACER_ADDRESS=$TRACER_ADDRESS

    depends_on:
      - mq
  

  trace:
    image: jaegertracing/all-in-one:1.47
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    
    

  companion:
    image: transloadit/companion:sha-a74ae35
    environment:
      COMPANION_DOMAIN: "http://companion.${ENVIRONMENT}mlmodelscope.org"
      COMPANION_DATADIR: "/data"

  mq:
    image: rabbitmq:3-management-alpine
    depends_on:
      - consul
    environment:
      RABBITMQ_ERLANG_COOKIE: "$MQ_ERLANG_COOKIE"

  consul:
    image: hashicorp/consul:1.12
    command: "agent -bootstrap=1"
