version: "3.9"
services:
  api:
    build:
      context: ./api/
      dockerfile: ../docker/Dockerfile.api-debug

    ports:
      - "2345:2345"

  uploader:
    build:
      context: ./uploader/
      dockerfile: ../docker/Dockerfile.uploader

networks:
  traefik:
    name: traefik
