version: "3.8"
services:
  api:
    build:
      context: ./api/
      dockerfile: ../docker/Dockerfile.api

    depends_on:
      - db
      - mq

    ports:
      - "8080:8080"


  db:
    image: postgres:14.1

    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DBNAME"

    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d/

networks:
  traefik:
    name: traefik
    attachable: true
