version: "3.8"
services:
  api:
    networks:
      - default
      - traefik

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-api.rule=Host(`api.${ENVIRONMENT}mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-api.entrypoints=websecure"
        - "traefik.http.routers.mlmodelscope-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.mlmodelscope-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowMethods=GET,OPTIONS,PUT"
        - "traefik.http.middlewares.add-cors.headers.accesscontrolalloworiginlist=https://staging.mlmodelscope.org,http://localhost:3000"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowCredentials=true"
        - "traefik.http.middlewares.add-cors.headers.accessControlAllowHeaders=origin,x-requested-with,content-type,accept,x-request-id"
        - "traefik.http.middlewares.add-cors.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.add-cors.headers.addvaryheader=true"
        - "traefik.http.routers.mlmodelscope-api.middlewares=add-cors"

  companion:
    networks:
      - default
      - traefik

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-companion.rule=Host(`companion.${ENVIRONMENT}mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-companion.entrypoints=web"
        - "traefik.http.services.mlmodelscope-companion.loadbalancer.server.port=3020"
        - "traefik.http.routers.mlmodelscope-companion.middlewares=add-cors"

  mq:
    networks:
      - default
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.mlmodelscope-mq.rule=Host(`mq${ENVIRONMENT}.mlmodelscope.org`)"
        - "traefik.http.routers.mlmodelscope-mq.entrypoints=websecure"
        - "traefik.http.routers.mlmodelscope-mq.tls.certresolver=letsencrypt"
        - "traefik.http.services.mlmodelscope-mq.loadbalancer.server.port=15672"
    volumes:
      - staging-rabbit-efs:/var/lib/rabbitmq/mnesia

networks:
  traefik:
    external: true
    name: traefik

volumes:
  staging-rabbit-efs:
    external: true