version: "3.8"
services:
  api:
    image: "$DOCKER_REGISTRY/mlmodelscope-api:$API_VERSION"

    environment:
      - DB_DBNAME=$DB_DBNAME
      - DB_DRIVER=$DB_DRIVER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - MQ_HOST=$MQ_HOST
      - MQ_PORT=$MQ_PORT
      - MQ_USER=$MQ_USER
      - MQ_PASSWORD=$MQ_PASSWORD

    depends_on:
      - mq

  trace:
    image: jaegertracing/all-in-one:1.21.0
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  uploader:
    image: "$DOCKER_REGISTRY/mlmodelscope-uploader:$UPLOADER_VERSION"
    ports:
      - "8089:80"

  mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "$MQ_USER"
      RABBITMQ_DEFAULT_PASS: "$MQ_PASSWORD"
    ports:
      - "15672:15672"
      - "5672:5672"