version: "3.8"
services:
  api:
    build:
      context: ./api/
      dockerfile: ../docker/Dockerfile.api

    depends_on:
      - db
      - mq
      - traefik

    networks:
      - default
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mlmodelscope-api.rule=Host(`api.${ENVIRONMENT}mlmodelscope.org`)"
      - "traefik.http.routers.mlmodelscope-api.entrypoints=web"
      - "traefik.http.services.mlmodelscope-api.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.add-cors.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,DELETE"
      - "traefik.http.middlewares.add-cors.headers.accesscontrolalloworiginlist=http://local.mlmodelscope.org,http://localhost:3000"
      - "traefik.http.middlewares.add-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.add-cors.headers.accessControlAllowHeaders=origin,x-requested-with,content-type,accept,x-request-id"
      - "traefik.http.middlewares.add-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.add-cors.headers.addvaryheader=true"
      - "traefik.http.routers.mlmodelscope-api.middlewares=add-cors"

    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  companion:
    env_file:
      - .env.companion

    depends_on:
      - traefik

    networks:
      - default
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mlmodelscope-companion.rule=Host(`companion.${ENVIRONMENT}mlmodelscope.org`)"
      - "traefik.http.routers.mlmodelscope-companion.entrypoints=web"
      - "traefik.http.services.mlmodelscope-companion.loadbalancer.server.port=3020"
      - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowMethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.add-cors-companion.headers.accesscontrolalloworiginlist=http://local.mlmodelscope.org"
      - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.add-cors-companion.headers.accessControlAllowHeaders=origin,content-type,accept,uppy-versions"
      - "traefik.http.middlewares.add-cors-companion.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.add-cors-companion.headers.addvaryheader=true"
      - "traefik.http.routers.mlmodelscope-companion.middlewares=add-cors-companion"

    volumes:
      - /tmp/companion_data:/data

  db:
    image: postgres:14.1

    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DBNAME"

    ports:
      - "15432:5432"

    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d/

  mq:
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  consul:
    volumes:
      - ./docker/consul/server.json:/consul/config/server.json:ro
      - consul_data:/consul/data

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.file.filename=/root/mlmodelscope-www.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"
      - "8080:8080"

    networks:
      - traefik

    volumes:
      - ./docker/mlmodelscope-www.yml:/root/mlmodelscope-www.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

### Monitoring services

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.grafana.rule=Host(`monitoring.${ENVIRONMENT}mlmodelscope.org`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    networks:
      - default
      - traefik

    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./docker/grafana/dashboards:/dashboards

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  traefik:
    name: traefik
    attachable: true

volumes:
  consul_data:
  prometheus_data:
  grafana_data:
